export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const LOAD_INGREDIENTS_FAILED = 'LOAD_INGREDIENTS_FAILED';

export const BURGER_ORDER_SUCCESS = 'BURGER_ORDER_SUCCESS';
export const BURGER_ORDER_FAIL = 'BURGER_ORDER_FAIL';
export const BURGER_ORDER_LOAD = 'BURGER_ORDER_LOAD';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_LOAD = 'FETCH_ORDERS_LOAD';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_LOAD = 'AUTH_LOAD';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';